// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: people.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createPeople = `-- name: CreatePeople :one
INSERT INTO people (name, surname, patronymic, age, gender, nationality)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, surname, patronymic, age, gender, nationality, created_at, updated_at
`

type CreatePeopleParams struct {
	Name        string
	Surname     string
	Patronymic  sql.NullString
	Age         int32
	Gender      string
	Nationality string
}

func (q *Queries) CreatePeople(ctx context.Context, arg CreatePeopleParams) (Person, error) {
	row := q.db.QueryRowContext(ctx, createPeople,
		arg.Name,
		arg.Surname,
		arg.Patronymic,
		arg.Age,
		arg.Gender,
		arg.Nationality,
	)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Surname,
		&i.Patronymic,
		&i.Age,
		&i.Gender,
		&i.Nationality,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
